### ISSUE TITLE
502 Bad Gateway error

### ISSUE THREAD

**Issue by mareeba** [evertramos/wordpress-docker-letsencrypt#7]
Have followed this to the letter and this is the fourth consecutive time I am getting either 502 or 504 gateway errors.

Have previously setup a working ghost-blog container following:
https://blog.mathewmerrick.com/2017/09/19/docker-nginx-letsencrypt-ghost/

This confirms that the nginx proxy is working as it should.

The only other thing of note is that `docker ps -a` shows that the wordpress container keeps trying to restart for some reason?!

Any thoughts?

**Comment by mareeba** [comment]
Also noticed the wordpress container is giving the following errors (using the default usernames and passwords from your example):

`wordpress    | MySQL "CREATE DATABASE" Error: Access denied for user 'user_name'@'%' to database 'wordpress'`

**Comment by fivestones** [comment]
I'm having the exact same two problems: 502 gateway error, and `wordpress | MySQL "CREATE DATABASE" Error: Access denied for user 'user_name'@'%' to database 'wordpress'`. Any idea how to fix these? Thanks!

**Comment by sharethl** [comment]
Use root for db solved the restarting issue.
WORDPRESS_DB_USER: root
But I still get the 502 gateway error.

**Comment by sharethl** [comment]
I solved this issue by clone both gits, and do it from beginning.
on docker-compose-letsencrypt-nginx-proxy-companion, this step will cause issues. 
curl https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl > nginx.tmpl

**Comment by evertramos** [comment]
Hello @mareeba @fivestones @sharethl, 

I was away for health reasons... sorry my late reply. 

I have fixed with a few improvments our webproxy (https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion) and fixed our wordpress with correct and ready configuration to work with our webproxy. Please check it working at https://wordpress.budhi.com.br we only got webproxy running and after that got this repo running with basic configuration in `.env` file and it worked fine. 

Please let me know if you face any new issue.

Best regards,
